import React from 'react'


export default () => {
    return <div className='font-pop text-white'>
        <h1 id="privacy"><strong>Privacy Policy</strong></h1>
        <p>This Privacy Policy (&quot;Policy&quot;) describes how information about you is collected, used, and disclosed by Myzanga.com, (&quot;Myzanga.com) &quot;), when you use our websites, mobile applications, and other online products and services (collectively, &quot;Services&quot;) or otherwise interact with us.</p>
        <p>At Myzanga.com, we are committed to protecting your privacy and creating a safe and secure online environment for anyone who visits or uses our site. All information is confidential and is never sold, rented, or otherwise shared with another business other than to help us provide the Services listed on our website. By visiting Myzanga.com, you are accepting the practices described in this Privacy Policy.</p>
        <p>If you have questions regarding this Policy or the collection of personal information, you may contact us using the information provided in the contact information section at the end of this Policy.</p>
        <p><strong>Information We Collect</strong></p>
        <p>Myzanga.com collects information that identifies, relates to, describes, references, is capable of being associated with, or could reasonably be linked, directly or indirectly, with a particular consumer or device (&quot; <strong>personal information</strong>&quot;). The categories of personal information that Myzanga.com may collect include:</p>
        <ul>
            <li><strong>Contact information</strong> (such as name, email address, mailing address, and phone number)</li>
            <li><strong>Personal identifiers</strong> (such as Social Security Number (SSN), date of birth, employee identification number, Taxpayer Identification Number (TIN), other DBA number(s), other government issued identification(s), account name, online identifier, and signature)</li>
            <li><strong>Financial information</strong> (such as bank, credit or debit card number, account type, routing number, bank institution name, account balances, credit history, investment activity, income or source of funds, and payment/transaction history)</li>
            <li><strong>Commercial information</strong> (such as primary business address, secondary business address, ownership information, products or services purchased, obtained, or considered, or other purchasing or consuming histories or tendencies, home purchase information, such as the address, type of home, and price range of the home you are interested in buying or selling, records of personal property)</li>
            <li><strong>Professional or employment-related information</strong> (such as occupation, title, performance evaluations, and prior employment history)</li>
            <li><strong>Demographic information</strong> (such as age, date of birth, gender, race, color, origin, citizenship, and ethnicity)</li>
            <li><strong>Personal characteristics</strong> (such as marital status and familial information)</li>
            <li><strong>Geolocation data</strong> (such as city/state, zip code, physical location or movements)</li>
            <li><strong>Internet or other Electronic Network Activity information</strong> (such as log information, IP address, access times, operating system, browser type and language, Internet service provider, and website interactions and browsing history)</li>
            <li><strong>Inferences drawn</strong> from the above categories of personal information reflecting your preferences, characteristics, behaviors, psychological trends, attitudes and abilities</li>
        </ul>
        <p>We may combine the above categories of information with other information we collect about you in order to improve our Services. For example, we may combine the information you provide to us, such as the type of home and price range of the home you are interested in buying or selling with other information we have collected about you or from you.</p>
        <p>In addition to the above categories, you may choose to provide us with additional pieces of information when you fill in a form, update or add information to your account, apply for a job, or interact with us in other ways.</p>
        <p><strong>How We Collect Personal Information</strong></p>
        <p>Myzanga.com collects information from a variety of sources. For example, we may collect information you provide directly to us, such as when you use the Services to compare the relevance of agents in your area of interest, request that we contact you to match you with an agent, provide feedback and rate your experiences using the Services, sign up for our mailing list, or when you call, email or otherwise communicate with us.</p>
        <p>The following are the categories of sources from which we may collect your personal information:</p>
        <ul>
            <li>Directly from you and other consumers through your interactions with us, such as when you use our services or purchase our products</li>
            <li>Through our websites, when you send us an email or complete a form requesting personal information</li>
            <li>From government agencies or public records</li>
            <li>Through automated technologies and online browser tools, including the use of cookies</li>
            <li>From third party service providers or business partners</li>
        </ul>
        <p>If you choose to submit any personal information relating to other people, you represent that you have the authority to do so and permit us to use the information in accordance with this Policy.</p>
        <p><strong>Use of Personal Information</strong></p>
        <p>We may use the personal information we collect for one, more or all of the following purposes:</p>
        <ul>
            <li><strong>Perform our Services and Respond to Requests.</strong> We may use personal information to fulfill requests, process payments, and perform other services requested by you.</li>
            <li><strong>Protection and Security.</strong> We may use personal information to protect the security and integrity of Myzanga.com our users, and others.</li>
            <li><strong>Administrative Communications.</strong> We may use personal information to send you important information regarding our services, such as changes to our terms, conditions, and policies and/or other administrative information.</li>
            <li><strong>Marketing Communications.</strong> We may use personal information to show you promotions or content based on your interests. You may opt out from receiving marketing communications, as described in the &quot;Your Rights&quot; section.</li>
            <li><strong>Research and Surveys.</strong> We may use personal information from you, our service providers, publicly available sources and other third parties to conduct research.</li>
            <li><strong>Internal Business Purposes.</strong> We may use personal information collected from the categories mentioned for our internal business purposes, such as data analysis, audits, developing new offerings, and monitoring or improving the use and satisfaction of our services or to evaluate or conduct a merger, divestiture, restructuring, reorganization, dissolution, or other sale or transfer of some or all of Myzanga.com&#39;s assets in which personal information held by Myzanga.com about our website users is among the assets transferred.</li>
            <li><strong>Testimonials and Reviews.</strong> We may display personal testimonials of satisfied customers on our site in addition to other endorsements. By submitting such information, you grant Myzanga.com the right to post and publish such information at our sole discretion. With your consent we may post your testimonial along with your name.</li>
            <li><strong>Legal and Regulatory.</strong> We may use personal information to comply with our legal or regulatory obligations, defend legal claims or cooperate with law enforcement.</li>
            <li><strong>Pairing/Matching Services</strong>. We may use the information provided to pair/match you with other users for the purpose not limited to rent sharing, cohabitation, processing for mortgage, crowd funding, investment pool and other services that may require your information.</li>
        </ul>
        <p><strong>Sharing Personal Information</strong></p>
        <p>Myzanga.com may disclose your personal information as described above to a third party for a business purpose. When we disclose personal information for a business purpose, we enter a contract that describes the purpose and requires the recipient to both keep that personal information confidential and not use it for any purpose except performing the contract.</p>
        <p>We may share your personal information with the following entities:</p>
        <ul>
            <li><strong>Affiliated Entities.</strong> We may share your personal information to our subsidiaries and corporate affiliates, including future subsidiaries and affiliates of Myzanga.com to use your information consistent with this Policy.</li>
            <li><strong>Third Party Service Providers.</strong> We may share personal information with third party service providers who provide us with services, such as data analysis, online advertising, payment processing, order fulfillment, IT services, customer service, and other similar services. We grant our service providers access to personal information only to the extent needed for them to perform their functions, and require them to protect the confidentiality and security of such personal information.</li>
            <li><strong>Commercial Partners.</strong> We may share personal information with unaffiliated third parties who partner with us to deliver our services or on our commercial activities. Depending on the choices you have made and the nature of the joint activity, these third parties may contact you regarding products or services of interest. However, we do not sell personal information to unaffiliated third parties for their own marketing purposes.</li>
            <li><strong>Business Transfers or Assignments.</strong> In the event of any reorganization, merger, sale, joint venture, assignment, transfer or other disposition of all or any portion of our business, assets or stock (including without limitation in connection with any bankruptcy or similar proceedings), we may transfer any information that we collect from site users or offline to a third party.</li>
            <li><strong>Law Enforcement; Emergencies; Compliance.</strong> We may disclose personal information about you to others as we believe to be appropriate: (i) under applicable law including laws outside your country of residence; (ii) to comply with legal process (iii) to respond to requests from public and government authorities including public and government authorities outside your country of residence; (iv) to enforce our terms and conditions; (v) to protect our operations and property interest; (vi) to protect the rights, privacy, safety or property of Myzanga.com, our employees, users of our service, or others; and (vii) to permit us to pursue available remedies or limit the damages that we may sustain.</li>
            <li><strong>At your direction.</strong> We may disclose your personal information as you otherwise consent to or request, such as to real estate agents and potential pre-approved cash buyers, as requested by you as part of our matching service.</li>
        </ul>
        <p><strong>In the preceding twelve (12) months, Myzanga.com has not sold any personal information for money. However, we may share your personal information with third parties and service providers for the purposes described in this Policy.</strong></p>
        <p><strong>Your Rights and Choices</strong></p>
        <p>Depending on your jurisdiction, applicable law may entitle you to certain rights and choices as it pertains to your personal information, including the right:</p>
        <ul>
            <li>To know the categories and/or specific pieces of personal information collected about you, including whether your personal information is sold or disclosed and the purpose, and with whom your personal information was shared;</li>
            <li>To request deletion of personal information;</li>
            <li>To access a copy of the personal information we retain about you;</li>
            <li>To opt-out of the sale of personal information; and</li>
            <li>To non-discrimination based on the exercise of a consumer&#39;s privacy rights.</li>
        </ul>
        <p>The Terms of this Policy shall be governed by and construed in accordance with Nigerian law and the parties agree that any disputes will be settled in Nigerian courts. Should any provision of these Policies be determined to be invalid or unenforceable by any court having competent jurisdiction, then the invalid or unenforceable provision will be replaced with a provision that reflects the intent of the original provision, to the extent permitted by applicable law and all other provisions of these Terms of Use shall remain in full force and effect.</p>
        <p>Please note that a portion of the information collected and processed by Myzanga.com may be out of scope for certain individual rights as it falls under exemptions for information collected under applicable state or federal laws.</p>
        <p><strong>Exercising Your Rights</strong></p>
        <p>In connection with promotions or other special projects, we may ask you specifically whether you have objections against a certain kind of data use or sharing. If you opt-out under such circumstances, we will respect your decision.</p>
        <p>If personal information you have submitted to us is no longer accurate, current, or complete, and you wish to update it, please contact us and upon appropriate request we will usually be glad to update or amend your information, but we reserve the right to use information obtained previously to verify your identity or take other actions that we believe are appropriate.</p>
        <p>To exercise any other rights as described in this Policy, please submit a request by contacting us using the contact information at the end of this Policy. We reserve the right to verify your identity in connection with any requests regarding personal information to help ensure that we provide the information we maintain to the individuals to whom it pertains, and allow only those individuals or their authorized representatives to exercise rights with respect to that information.</p>
        <p>If you are an authorized agent or parent/guardian making a request on behalf of an individual or your minor child, we may require and request additional information to verify that you are authorized to make that request.</p>
        <p>We reserve the right to deny your request if we cannot verify your identify. Where we deny your request in whole or in part, we will inform you of the denial.</p>
        <p>We will not restrict or deny you access to our services because of choices and requests you make in connection with your personal information.</p>
        <p><strong>Security and Protection of Personal Information</strong></p>
        <p>The security of your personal information is important to us. Thus, Myzanga.com has taken reasonable steps to help protect the personal information our users share with us in an effort to prevent loss, misuse, and unauthorized access, disclosure, alteration, and destruction.</p>
        <p>We endeavor to protect the personal information submitted to us, both during transmission and once we receive it. No method of transmission over the Internet, or method of electronic storage, is 100% secure. Therefore, we cannot guarantee its absolute security. We urge you to exercise caution when transmitting personal information over the Internet. If you have questions about security on our Web site, you can contact us at <a href="mailto:contact@Myzanga.com">contact@Myzanga.com</a></p>
        <p><strong>Links to Third Party Sites</strong></p>
        <p>Our website includes links to other websites whose privacy practices may differ from those of Myzanga.com. If you submit personal information to any of those sites, your information is governed by their privacy policies. We encourage you to carefully read the privacy policy of any website you visit.</p>
        <p>Our website also includes Social Media Features, such as the Facebook Like/Share button, the Twitter Tweet button and other social sharing buttons or interactive mini-programs that run on our site. These Features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the Feature to function properly. Social Media Features and Widgets are either hosted by a third party or hosted directly on our website. Your interactions with these Features are governed by the privacy policy of the company providing it.</p>
        <p><strong>Children and Minors</strong></p>
        <p>Myzanga.com does not direct services to individuals under the age of Eighteen (18) and we do not sell the personal information of minors under 18 years of age. If you are under age 18, please do not submit personal information to us. If you are a parent and become aware that your child has provided us with information, please contact us using one of the methods specified below and we will work with you to address this issue.</p>
        <p><strong>Cookies / Website Usage</strong></p>
        <p>When you access our website, your personal information may be collected by cookies and other similar technologies. Technologies such as: cookies, beacons, tags and scripts are used by Myzanga.com and our marketing partners and analytics or service providers. These technologies are used in analyzing trends, administering the site, tracking users&#39; movements around the site anonymously and to gather demographic information about our user base as a whole. We may receive reports based on the use of these technologies by these companies on an aggregated basis. If you reject cookies, you may still use our site, but your ability to use some features or areas of our site may be limited.</p>
        <p><strong>Behavioral Targeting</strong></p>
        <p>We partner with a third party to either display advertising on our web site or to manage our advertising on other sites. Our third-party partner may use technologies such as cookies to gather information about your activities on this site and other sites in order to provide you advertising based upon your browsing activities and interests. If you wish to not have this information used for the purpose of serving you interest-based ads, you may opt-out by mailing an opt out request to <a href="mailto:admin@myzanga.com">admin@myzanga.com</a>. Please note this does not opt you out of being served ads. You will continue to receive generic ads.</p>
        <p><strong>Testimonials and Reviews</strong></p>
        <p>Users may perform ratings and reviews of our lenders and real estate professionals. By submitting such information, you grant Myzanga.com the right to post and publish such information at our sole discretion. We also display personal testimonials of satisfied customers on our site in addition to other endorsements. With your consent we may post your testimonial along with your name.</p>
        <p><strong>Changes to Our Privacy Policy</strong></p>
        <p>Myzanga.com reserves the right to amend this Policy at our discretion and at any time. Endevour to check for updates every time you use the website. <strong>Your continued use of our Services following the posting of changes constitutes your acceptance of such changes.</strong></p>
        <p><strong>Contact Information</strong></p>
        <p>Myzanga.com is solely owned and operated by Sales Force Derivative Company Ltd. (SFDC) If you have any questions or comments about this Policy, the ways in which Myzanga.com collects and uses your information described in Policy, your choices and rights regarding such use, or wish to exercise your applicable rights, please do not hesitate to contact us at:</p>
        <p><strong>Email:</strong> <a href="mailto:contact@myzanga.com">contact@myzanga.com</a></p>

    </div>
}