import React from 'react'


export default () => {
    return <div className='font-pop text-blue'>
        <h1 id="terms"><strong>Terms of Service</strong></h1>
        <p><strong>Use of Our Service</strong></p>
        <p>Matchmaking is the core of what we do for real estate. When the time is right, we make a professional introduction between you and one of our Real Estate Agent partners. The service that we provide to both buyers and sellers of real estate and real estate professionals is governed by a few terms that are outlined below.</p>
        <p>Because we are an online service, we don&#39;t ask you to deal with and physically sign a lengthy contract. The terms of our contract with you are set forth below in plain language. If you don&#39;t agree with the terms, then we ask you please to leave this Web site. If you do use this Web site, then that action will serve as your agreement to be bound by our terms of service.</p>
        <p><strong>Terms for Broker and Agents</strong></p>
        <p>Real estate professionals who are involved with and use our Web site must agree with the following terms:</p>
        <ol>
            <li>You grant <a href="https://www.myzanga.com/">Myzanga.com</a> permission to display on our Web site and elsewhere information that we have gathered or you have supplied related to any of the real estate transactions that you have handled as a real estate professional. This information helps your potential clients better understand your specialties.</li>
            <li>Creating a profile on Myzanga.com is completely free. However, there are different services available that require subscription, payments, referral bonus, commissions and fees, the terms for this is located here: <a href="www.myzanga.com/fees">fees</a>, this is how we earn money and allows us to continue to provide our services to you.</li>
            <li>We created a proprietary pseudo currency &quot;Zanga Token&quot; to be used within the website, mobile App and other medium for transactions within the platform for simplicity, to curb the effect of fluctuations with fiat currencies and manage exchange rates within the community.</li>
            <li>You are responsible for maintaining your own real estate license and for following all applicable real estate laws regarding disclosures, documentation and other brokerage responsibilities. In addition, you are responsible for the real estate brokerage services provided to your clients and agree to indemnify, defend and hold Myzanga.com harmless from any claims, costs, and damages incurred by Myzanga.com arising from claims by your clients regarding the brokerage services you have provided.</li>
            <li>Your participation in our service is voluntary and can be terminated by either of us for any reason at any time with written notice. However, any referrals made prior to such termination are still bound by this agreement, and Referral Fees will be due upon close of any transactions resulting from such referrals.</li>
            <li>In connection with the referrals, you agree to be contacted by Myzanga.com and its referrals via phone, email, mail or other reasonable means, and you further agree that you will not provide the referrals to any other party without our written consent.</li>
            <li>You may initiate or receive a call from a Myzanga.com representative or one of the referrals of myzanga.com. If you do so, Myzanga.com may create a digital audio recording of the call. You acknowledge and agree that your phone call may be recorded for quality assurance purposes.</li>
            <li>Myzanga.com created a proprietary system that allows users share property list/links via social media, electronic media and any other media for the purpose to earn commissions, fees, bonuses and rewards to aid in the sales, purchase and rental of the said property.</li>
            <li>Within myzanga.com embeds a system that pair/match people/businesses towards not limited to Renting, purchase, lease, investing and promotion of property within and outside the community for profit, rewards, bonuses and commissions.</li>
            <li>Any information that you provide to Myzanga.com shall be accurate, complete and owned by you, and you agree to update any information that is or becomes inaccurate. Of course, if we discover that any information is inaccurate we may correct it ourselves. You hereby grant us permission to e-mail or display your Profile (including your name, likeness, contact information and transaction details) and such other information as may be supplied by you on or from our Web site &quot;<a href="https://www.homelight.com/">www.Myzanga.com</a>&quot; and such other partner and affiliate websites as we believe advisable for marketing purposes.</li>
            <li>You agree that we may modify the services provided, these terms of service or the price charged for our services at any time. We will send you an email in advance of any significant changes of our services, terms of service or prices, and you agree that your continued use of our services after the notice period means that you accept the new terms and any subsequent referrals or services shall be governed by the new terms.</li>
        </ol>
        <p><strong>Terms for Buyers and Sellers</strong></p>
        <p>All non-real estate professionals (including prospective Buyers and Sellers and their representatives) who are involved with and use our Web site must agree with the following terms:</p>
        <ol>
            <li>When the time is right, we may make a professional introduction between you and one of our partners, including our real estate agent partners. Of course, this introduction involves sharing the contact information of each party with the other. When you submit information to Myzanga.com for a request, you authorize us to use and provide this information to make an introduction. By providing this information to us, you consent to being contacted by us and by our partners via phone, email, mail or other reasonable means.</li>
            <li>For us to help you, we need you to provide information that is accurate and complete, especially your contact information so that our Real Estate Agent partners can contact you quickly and efficiently. We reserve the right to suspend or terminate access to anyone who supplies information that is inaccurate or misleading.</li>
            <li>You understand that while Myzanga.com may refer real estate professionals, we do not perform real estate brokerage services. Any Real Estate brokerage activities are performed by local Real Estate Professionals that have been referred to you. We do not endorse, recommend or otherwise know the terms of any agreement between you and a real estate professional.</li>
            <li>You understand that for our services we may receive payment (a referral fee) that may be a percentage of the commission received by the professionals involved in the real estate transaction. There is no charge to you. Any payment is due based on a separate agreement between us and the professional involved. Your use of our services constitutes your acknowledgment of, and agreement to, this compensation arrangement.</li>
            <li>You understand that we shall reward, pay, settle users that use our proprietary system to share property list/links, hence need for sellers/brokers and buyer is subjected to fees, commissions and rewards to enable these compensations.</li>
            <li>Your participation in our service is voluntary and can be terminated by either of us for any reason at any time with written notice. However, any referrals made prior to such termination are still bound by the agreement that we may have with a real estate professional.</li>
            <li>You agree that we may modify the services provided or these terms of service at any time. We will notify you in advance of any significant changes of our services, and you agree that your continued use of our services after the notice period means that you accept the new terms and any subsequent services shall be governed by the new terms.</li>
            <li>You may initiate or receive a call from a Myzanga.com representative or one of our agent partners of myzanga.com. If you do so, Myzanga.com may create a digital audio recording of the call. You acknowledge and agree that your phone call may be recorded for quality assurance purposes only.</li>
        </ol>
        <p><strong>Additional Terms</strong></p>
        <p>All who are involved with and use our Web site must agree with the following additional terms:</p>
        <ul>
            <li>It is the policy of Myzanga.com to respond to all claims of intellectual property infringement. We will promptly investigate notices of alleged infringement and will take appropriate actions required under the law.</li>
            <li>Though myzanga.com strives to encourage a respectful user experience through features like the double opt-in that only allows users to communicate if they have both indicated interest in pairing/matching for the purpose of letting, purchase investing. It is not responsible for the conduct of any user on or off of the Service. You agree to use caution in all interactions with other users, particularly if you decide to communicate off the Service or meet in person. You agree that you will not provide your financial information (for example, your credit card or bank account information), or wire or otherwise send money, to other users.</li>
            <li>You are solely responsible for your interactions with other users. You understand that myzanga.com does not conduct criminal background checks on its users or otherwise inquire into the background of its users. Myzanga.com makes no representations or warranties as to the conduct of users. Myzanga.com reserves the right to conduct – and you agree that myzanga.com may conduct - any criminal background check or other screenings (such as credit bureau, criminal registry searches) at any time using available public records.</li>
            <li><p>Myzanga.com intends that the information contained on our Web site be accurate and reliable; however, errors sometimes occur. In addition, we may make changes and improvements to the information provided at any time. Accordingly, we do not guarantee the accuracy of any information available on this Web site, and are not responsible for any errors, omissions, or misrepresentations and any information should be independently verified.</p>
            </li>
            <li><p>To protect our service, you agree to refrain from the following prohibited activities: (a) submitting materials that are patently offensive to the online community, such as content that promotes racism, bigotry, hatred or physical harm of any kind against any group or individual; (b) engaging in activities or submitting materials that could be harmful to minors; (c) engaging in activity or submitting materials that harasses or advocates harassment of another person; (d) engaging in activity that involves the transmission of &quot;junk mail&quot; or unsolicited mass mailing or &quot;spam&quot; or harvesting or otherwise collecting personally identifiable information about Web site users, including names, phone numbers, addresses, email addresses, (collectively, &quot;User Data&quot;) without their consent; (e) engaging in activity, or submitting materials, or promoting information that is false, misleading or promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libelous; (f) submitting materials that contain restricted or password only access pages, or hidden pages or images; (g) submitting materials that displays pornographic or sexually explicit material of any kind; (h) submitting materials that provide instructional information about illegal activities such as making or buying illegal weapons, violating someone&#39;s privacy, or providing or creating computer viruses; (i) submitting materials that contain viruses, Trojan horses, worms, or any other similar forms of malware, (j) engaging in activities or submitting materials that solicit passwords or personally identifiable information for unlawful purposes from other users; (k) engaging in unauthorized commercial activities and/or sales without our prior written consent such as advertising, solicitations, contests, sweepstakes, barter, and pyramid schemes; (l) using any robot, spider, other automatic device, or manual process to monitor, copy, or &quot;scrape&quot; web pages or the content contained in the Web site or for any other unauthorized purpose without our prior written consent; (m) using any device, software, or routine to interfere or attempt to interfere with the proper working of the Web site; (n) decompiling, reverse engineering, or disassembling the software or attempting to do so; or (o) taking any action that imposes an unreasonable or disproportionately large load on the Web site or our hardware and software infrastructure or that of any of our licensors or suppliers.</p>
            </li>
            <li>You agree to the following limitation: The web site and the information, software, products and services associated with it are provided &quot;As is.&quot; Myzanga.com and/or its suppliers, participating lenders, or real estate professionals disclaim any warranty of any kind, whether express or implied, as to any matter whatsoever relating to the web site and any information, software, products and services provided herein, including without limitation the implied warranties of merchantability, fitness for a particular purpose, title, and non-infringement. Use of myzanga.com&#39;s service is at your own risk. We and/or its suppliers, are not liable for any direct, indirect, punitive, incidental, special or consequential damages or other injury arising out of or in any way connected with the use of our services or with the delay or inability to use the web site, or for any information, software, products and services obtained through the web site, or otherwise arising out of the use of the web site, whether resulting in whole or in part, from breach of contract, tortious behavior, negligence, strict liability or otherwise, even if we and/or its suppliers had been advised of the possibility of damages.</li>
            <li>You also agree to the following: In no event shall Myzanga.com or our suppliers be liable for lost profits or any special, incidental or consequential damages (however arising, including negligence) arising out of or in connection with this agreement.</li>
            <li>You also agree to the following dispute resolution, arbitration, and class action waiver: Instead of suing in Court, you and Myzanga.com agree to arbitrate all disputes between you and Myzanga.com or any of Sales Force Derivative Company Ltd. (SFDC)&#39;s agents, representatives, or partners acting on Sales Force Derivative Company Ltd. (SFDC)&#39;s behalf, on an individual basis, not on a class-wide or consolidated basis. Unless we each agree otherwise, the Arbitration will be conducted by a single, neutral arbitrator and will take place in Nigeria. We each agree that we will only pursue arbitration on an individual basis and will not pursue arbitration on a class-wide or consolidated basis. We each agree that any arbitration will be solely between you and Myzanga.com (or Sales Force Derivative Company Ltd. (SFDC)&#39;s agents, representatives, or partners acting on Sales Force Derivative Company Ltd. (SFDC)&#39;s behalf). We each waive any rights to bring a class action or consolidated action. Exceptions: Either of us may bring qualifying claims in small claims court.</li>
            <li>Finally, you also agree to the following: These Terms of Service shall be subject to and construed in accordance with the laws of Federal Republic of Nigeria, without regard to its conflict of laws principles. If any part of these Terms of Service are determined to be invalid or unenforceable pursuant to applicable law including, but not limited to, the warranty disclaimers and liability limitations set forth above, then the invalid or unenforceable provision will be deemed superseded by a valid enforceable provision that most closely matches the intent of the original provision, and the remainder of the Agreement shall continue in effect. A printed version of this Agreement and of any notice given in electronic form shall be admissible in judicial or administrative proceedings based upon or relating to this agreement to the same extent and subject to the same conditions as other business documents and records originally generated and maintained in printed form. All rights not expressly granted herein are reserved to myzanga.com or agents Sales Force Derivative Company Ltd. (SFDC).</li>
            <li>Myzanga.com is operated in compliance with the laws of the Federal Republic of Nigeria; myzanga.com is solely owned and operated by Sales Force Derivative Company Ltd. With <strong>RC No: 1470685</strong>.</li>
        </ul>
        <p>For enquiry kind contact us via email <a href="mailto:contact@myzanga.com">contact@myzanga.com</a></p>

    </div>
}